name: flutter_chatgpt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  vibration: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
flutter:
  uses-material-design: true
